
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ?? DataSource Driver
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ?? YAML ????
    url: jdbc:shardingsphere:classpath:config-sharding.yaml